# Generated by Django 5.2 on 2025-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0029_add_existing_chartaggregateddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='Available credits for this tenant'),
        ),
    ]
