# Generated by Django 5.2 on 2025-10-29 12:27

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('excel_data', '0032_add_credits_only'),
    ]

    # No-op to keep migration history clean; credits handled in 0030
    operations = []
