# Generated by Django 5.2 on 2025-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0036_add_deactivated_at_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deletion_warning_email_sent',
            field=models.BooleanField(default=False, help_text='Whether deletion warning email has been sent (3 days before permanent deletion)'),
        ),
    ]
