# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0037_add_deletion_warning_email_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Holiday name', max_length=200)),
                ('date', models.DateField(help_text='Holiday date')),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National Holiday'), ('REGIONAL', 'Regional Holiday'), ('COMPANY', 'Company Holiday'), ('FESTIVAL', 'Festival'), ('OTHER', 'Other')], default='COMPANY', help_text='Type of holiday', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Holiday description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is active')),
                ('applies_to_all', models.BooleanField(default=True, help_text='If False, specify departments this holiday applies to')),
                ('specific_departments', models.CharField(blank=True, help_text='Comma-separated department names (if not applies_to_all)', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='excel_data.tenant')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'date'], name='holidays_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'is_active'], name='holidays_date_active_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'date', 'is_active'], name='holidays_tenant_date_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant', 'date', 'name')},
        ),
    ]

