# Generated by Django 5.2 on 2025-11-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0038_create_holiday_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holiday',
            new_name='holidays_tenant__d92347_idx',
            old_name='holidays_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='holiday',
            new_name='holidays_date_19f7a8_idx',
            old_name='holidays_date_active_idx',
        ),
        migrations.RenameIndex(
            model_name='holiday',
            new_name='holidays_tenant__18650e_idx',
            old_name='holidays_tenant_date_active_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('payroll_master', 'Payroll Master'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('payroll_master', 'Payroll Master'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
