# Generated by Django 5.2 on 2025-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0040_add_holiday_days_to_calculated_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday_days',
            field=models.IntegerField(default=0, help_text='Number of paid holidays in this period'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='holiday_days',
            field=models.IntegerField(default=0, help_text='Number of paid holidays in this period'),
        ),
    ]
