# Generated by Django 5.2 on 2025-11-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0041_attendance_holiday_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('UNMARKED', 'Unmarked'), ('HALF_DAY', 'Half Day'), ('PAID_LEAVE', 'Paid Leave'), ('OFF', 'Off Day')], max_length=10),
        ),
    ]
