# Generated by Django 5.2 on 2025-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0042_alter_dailyattendance_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unmarked_days',
            field=models.IntegerField(default=0, help_text='Number of days with unmarked attendance status'),
        ),
    ]
