# Generated by Django 5.2 on 2025-11-25 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0043_attendance_unmarked_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Ticket subject', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the ticket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response', models.TextField(blank=True, help_text='Admin response to the ticket', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='excel_data.tenant')),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='support_tic_tenant__c4e56a_idx'), models.Index(fields=['status', '-created_at'], name='support_tic_status_8239ad_idx'), models.Index(fields=['priority', '-created_at'], name='support_tic_priorit_563d3e_idx'), models.Index(fields=['created_by', '-created_at'], name='support_tic_created_0eacb2_idx')],
            },
        ),
    ]
