# Generated by Django 5.2 on 2025-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0044_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='average_days_per_month',
            field=models.DecimalField(decimal_places=2, default=30.4, help_text='Average days per month used for salary and OT rate calculations (default: 30.4)', max_digits=5),
        ),
    ]
