# Generated by Django 5.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0045_tenant_average_days_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='break_time',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Break time in hours to be deducted from shift hours for OT calculations (default: 0.5 hours = 30 minutes)', max_digits=5),
        ),
    ]

