# Generated by Django 5.2 on 2025-01-XX XX:XX
# Test migration to verify auto-migration functionality on server start

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0046_tenant_break_time'),
    ]

    operations = [
        # Empty migration - just for testing auto-migration functionality
        # This migration does nothing but can be used to verify that
        # the server automatically detects and applies pending migrations
        # when the server starts
    ]

