# Generated by Django 5.2 on 2025-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0047_test_migration_auto_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional attachment file for the ticket', null=True, upload_to='support_tickets/attachments/%Y/%m/%d/'),
        ),
    ]
