# Generated by Django 5.2 on 2025-12-02 08:31

import excel_data.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0048_add_attachment_to_support_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedsalary',
            name='sunday_bonus_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total bonus Sunday present days for this period', max_digits=5),
        ),
        migrations.AddField(
            model_name='calculatedsalary',
            name='weekly_penalty_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total penalty days added due to weekly absent rule for this period', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sunday_bonus_enabled',
            field=models.BooleanField(default=False, help_text='Enable Sunday bonus rule (if present more than N days in a week, upcoming Sunday is treated as bonus present day even if off day)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sunday_bonus_threshold',
            field=models.IntegerField(default=4, help_text='Number of present days in a week after which upcoming Sunday is treated as bonus present day (default: 4)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='weekly_absent_penalty_enabled',
            field=models.BooleanField(default=False, help_text='Enable weekly absent penalty rule (if absent more than N days in a week, add 1 penalty day)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='weekly_absent_threshold',
            field=models.IntegerField(default=4, help_text='Number of absent days in a week after which 1 penalty day is added (default: 4)'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional attachment file for the ticket', null=True, storage=excel_data.storage.R2Storage(), upload_to='support_tickets/attachments/%Y/%m/%d/'),
        ),
    ]
