# Generated by Django 5.2 on 2025-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0049_calculatedsalary_sunday_bonus_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='sunday_bonus_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total bonus Sunday present days for this period', max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='weekly_penalty_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total penalty days added due to weekly absent rule for this period', max_digits=5),
        ),
    ]
