# Generated by Django 5.2 on 2025-12-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0050_monthlyattendancesummary_sunday_bonus_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='weekly_rules_enabled',
            field=models.BooleanField(default=True, help_text='Enable weekly penalty rules for this employee (only applicable if tenant weekly rules are enabled)'),
        ),
    ]
