# Generated by Django 5.2 on 2025-12-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0051_add_weekly_rules_enabled_to_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedsalary',
            name='basic_salary_per_minute',
        ),
        migrations.RemoveField(
            model_name='calculatedsalary',
            name='sunday_bonus_days',
        ),
        migrations.RemoveField(
            model_name='monthlyattendancesummary',
            name='sunday_bonus_days',
        ),
    ]
