# Generated by Django 5.2 on 2025-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0052_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='penalty_ignored',
            field=models.BooleanField(default=False, help_text="If True, this day's ABSENT does not count toward weekly penalty threshold"),
        ),
    ]
