# Generated by Django 5.2 on 2025-12-22 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0053_dailyattendance_penalty_ignored'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('bulk_update', 'Bulk Update'), ('activate', 'Activate Employees'), ('deactivate', 'Deactivate Employees'), ('delete', 'Delete Employees')], max_length=50)),
                ('employee_count', models.IntegerField()),
                ('changes', models.JSONField()),
                ('reverted', models.BooleanField(db_index=True, default=False)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_updates', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_update_reverts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='excel_data.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['-performed_at', 'tenant'], name='excel_data__perform_cb8058_idx'), models.Index(fields=['action_id'], name='excel_data__action__8cf1ce_idx'), models.Index(fields=['reverted', 'tenant'], name='excel_data__reverte_7cd8d3_idx')],
            },
        ),
    ]
