# Generated by Django 5.2 on 2025-12-26 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0054_add_bulk_update_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(help_text='Hashed 4-digit PIN', max_length=128)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether PIN authentication is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.IntegerField(default=0, help_text='Number of consecutive failed PIN attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='PIN is locked until this time after too many failed attempts', null=True)),
                ('user', models.OneToOneField(help_text='User this PIN belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pin_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_pins',
            },
        ),
    ]
