# Generated by Django 5.2 on 2026-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0055_add_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='face_attendance_enabled',
            field=models.BooleanField(default=False, help_text='Enable face attendance feature for this tenant'),
        ),
    ]
