# Generated by Django 5.2 on 2026-01-27 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0057_employee_face_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('similarity_threshold', models.FloatField(default=0.55)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to='excel_data.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='excel_data.tenant')),
            ],
            options={
                'db_table': 'excel_data_face_embedding',
                'indexes': [models.Index(fields=['tenant', 'employee'], name='face_embedding_employee_idx')],
            },
        ),
    ]
