# Generated by Django 5.2 on 2026-01-27 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0058_faceembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out')], max_length=16)),
                ('recognized', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, help_text="Source channel, e.g. 'mobile', 'web', 'kiosk'", max_length=32)),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_logs', to='excel_data.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_logs', to='excel_data.tenant')),
            ],
            options={
                'db_table': 'excel_data_face_attendance_log',
                'indexes': [models.Index(fields=['tenant', 'event_time'], name='face_log_tenant_time_idx'), models.Index(fields=['tenant', 'employee', 'event_time'], name='face_log_employee_time_idx')],
            },
        ),
    ]
